### ISSUE TITLE
Is this based on some paper?

### ISSUE THREAD

**Issue by cesss** [david-sabata/Radiosity#4]
Hi! Is this implementation based in some paper or thesis? I’m looking for radiosity implementations with GPU acceleration.

**Comment by david-sabata** [comment]
This is an implementation of the most common radiosity algorithm. It's running on GPU, but please mind the date I wrote the code 🙂

Here's a video of running this code https://youtu.be/zYvdLD4Afy8

**Comment by cesss** [comment]
Thanks a lot! Do you mean that it’s based on the radiosity GPU approach from the Coombe/Lastra paper, or that you implemented directly it from the classical non-GPU papers from the 80s?

**Comment by david-sabata** [comment]
I'm not familiar with the Coombe/Lastra paper, but my lecturer and thesis leader might had been. He was giving guidance on the GPU implementation.

If you can outline the differences in the two approaches, I can probably tell you which one is closer.
My implementation divides the scene surfaces into patches, rendering each with unique color. Then it moves the camera to see what the patch sees in the scene, starting from the patches with the highest energy (=light sources). That view is rendered into memory and from the colors in the view the energy is distributed (=visible patches are lit). This process repeats until the undistributed energy in the scene is below some threshold. Most of the process is happening on GPU, leveraging tech like FBO

**Comment by cesss** [comment]
Yes, it seems you are implementing the classical canonical algorithm. The Combee/Lastra paper gives clues on how to implement radiosity on GPU, but based on a very old OpenGL version (the paper is from 1999-2001 IIRC).

Btw, one question: what are you using OpenCL for? I supposed it was an OpenGL implementation, but there’s an OpenCL header in the source...

**Comment by david-sabata** [comment]
OpenCL is used to process the rendered view from a patch. I split the texture into segments and use OpenCl to process the energy transfers in parallel

https://github.com/david-sabata/Radiosity/blob/master/source/Main.cpp#L451

**Comment by cesss** [comment]
Oh, that’s great! I’ll compile it this week, it looks promising if you managed to combine OpenGL and OpenCL in an efficient way!! If I get interesting results, I’ll tell you!!
